/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calcula_1_argument {
	int arg1;
	int arg2;
	int arg3;
};
typedef struct calcula_1_argument calcula_1_argument;

#define CALCULAPROG 0x20000001
#define OPERACIONES 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULA 1
extern  int * calcula_1(int , int , int , CLIENT *);
extern  int * calcula_1_svc(int , int , int , struct svc_req *);
extern int calculaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULA 1
extern  int * calcula_1();
extern  int * calcula_1_svc();
extern int calculaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calcula_1_argument (XDR *, calcula_1_argument*);

#else /* K&R C */
extern bool_t xdr_calcula_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
