/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"

int *
calcula_1_svc(int arg1, int arg2, int arg3,  struct svc_req *rqstp)
{
	static int  result;

	if(arg1==1) {
		result = arg2+arg3;
	} else if(arg1==2) {
		result = arg2-arg3;
	} else if(arg1==3) {
		result = arg2*arg3;
	} else {
		result = arg2/arg3;
	}

	return &result;
}
