/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "asociacion.h"

#define TAMA 128

void
asociacionprog_1(char *host)
{
	CLIENT *clnt;
	Estado  *result_1;
	ID ponerasociacion_1_arg1;
	Clave ponerasociacion_1_arg2;
	Valor ponerasociacion_1_arg3;
	ResultEntrada  *result_2;
	ID obtenerasociacion_1_arg1;
	Clave obtenerasociacion_1_arg2;
	Estado  *result_3;
	ID borrarasociacion_1_arg1;
	Clave borrarasociacion_1_arg2;
	ResultDiccionario  *result_4;
	ID enumerar_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, ASOCIACIONPROG, ASOCIACION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int opcion;
	int id;
	char str[TAMA];

	printf("Seleccione Opcción:\n1.-Insertar asociación\n2.-Obtener asociación\n3.-Borrar asociación\n4.-Enumerar\n5.-Salir\n");
	scanf("%d",&opcion);
	while(opcion!=5) {
		switch(opcion) {
			case 1:
				printf("INSERTAR ASOCIACIÓN");
				printf("Introduzca ID:");
				scanf("%d",&id);
				ponerasociacion_1_arg1 = id;
				//printf("Has escrito %d\n",ponerasociacion_1_arg1);
				printf("Introduzca Clave:");
				scanf("%s",str);
				ponerasociacion_1_arg2 = str;
				//printf("Has escrito %s\n",ponerasociacion_1_arg2);
				printf("Introduzca Valor:");
				scanf("%s",str);
				ponerasociacion_1_arg3 = str;
				//printf("Has escrito %s\n",ponerasociacion_1_arg3);
				result_1 = ponerasociacion_1(ponerasociacion_1_arg1, ponerasociacion_1_arg2, ponerasociacion_1_arg3, clnt);
				if (result_1 == (Estado *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				break;
			case 2:
				break;
			case 3:
				break;
			case 4:
				break;
			default:
				printf("Opción incorrecta. Seleccione Opcción:\n1.-Insertar asociación\n2.-Obtener asociación\n3.-Borrar asociación\n4.-Enumerar\n5.-Salir\n");
				break;
		}
		printf("Seleccione Opcción:\n1.-Insertar asociación\n2.-Obtener asociación\n3.-Borrar asociación\n4.-Enumerar\n5.-Salir\n");
		scanf("%d",&opcion);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	asociacionprog_1 (host);
exit (0);
}
